### ISSUE TITLE
Add some metadata event attributes to posthog implementation

### ISSUE THREAD

**Issue by andrewm4894** [netdata/dashboard#213]
We would like to add the following event attributes, derived from `/api/v1/info` as additional event attributes sent for each posthog event. This will provide a lot more context about a users session to help with product analytics and usage statistics. 

- netdata_version = version
- mirrored_host_count = count of mirrored_hosts
- alarms_normal = alarms.normal
- alarms_warning = alarms.warning
- alarms_critical = alarms.critical
- host_os_name = os_name
- host_os_id = os_id
- host_os_id_like = os_id_like
- host_os_version = os_version
- host_os_version_id = os_version_id
- host_os_detection = os_detection
- system_cores_total = cores_total
- system_total_disk_space = total_disk_space
- system_cpu_freq = cpu_freq
- system_ram_total = ram_total
- system_kernel_name = kernel_name
- system_kernel_version = kernel_version
- system_architecture = architecture
- system_vitrualization = virtualization
- system_virt_detection = virt_detection
- system_container = container
- system_container_detection = container_detection
- container_os_name = container_os_name
- container_os_id = container_os_id
- container_os_id_like = container_os_id_like
- container_os_version = container_os_version
- container_os_version_id = container_os_version_id
- host_collectors_count = count of collectors
- host_cloud_enabled = cloud-enabled
- host_cloud_available = cloud-available
- host_agent_claimed = agent-claimed
- host_aclk_available = aclk-available
- host_is_parent = _is_parent from host_labels
- mirrored_hosts_reachable = Count of reachable=true from mirrored_hosts_status
- mirrored_hosts_unreachable = Count of reachable=false from mirrored_hosts_status
- host_collector_modules = '|' separated string concatenated list of pluginfrom collectors e.g. apps.plugin|python.d.plugin|proc.plugin|proc.plugin… there should be one for each collector duplicates are ok in the string as we want the order to match that of host_collector_plugins.
- host_collector_plugins = '|' separated string concatenated list of modulefrom collectors e.g.  |redis|/proc/diskstats|/proc/softirqs|/proc/uptime … notice the “ “ at start of that list - that's ok. 

The event attributes can be set at the same time of the initial `posthog.register` call that we use to mask things like ip and host etc. 

https://github.com/netdata/dashboard/blob/posthog-test/src/domains/global/sagas.ts#L86 

This will mean that important metadata like netdata version etc will now be available as part of the agent telemetry and so will make things like spotting anomalies and bugs in usage behaviour by netdata version etc much much easier.

**Comment by andrewm4894** [comment]
Link to related confluence doc as fyi. https://netdata.atlassian.net/wiki/spaces/PM/pages/503447569/Agent+Telemetry+-+GA+migration

**Comment by andrewm4894** [comment]
@jacekkolasa can we include the new 

`is_k8s_node` from /info as host_is_k8s_node

**Comment by andrewm4894** [comment]
I should also say that if we can't generate any event attribute for some reason, eg if not available in the info endpoint then we should omit the event attribute from the posthog register call.

**Comment by jacekkolasa** [comment]
@andrewm4894 i've created an alpha release with this if you want to test:
/packaging/dashboard.version - `v2.12.0-alpha.2`
/packaging/dashboard. checksums - `ded3741a919649232e98e413119af443d72b0a87166961c5f6b3f594ec96efb2`

Will it help if I create a commit with new dashboard version here - https://github.com/andrewm4894/netdata/commits/posthog-dev ?

**Comment by andrewm4894** [comment]
closing ad done ty!
