### ISSUE TITLE
PostHog dev dashboard v2.12.0-alpha.5 release

### ISSUE THREAD

**Issue by andrewm4894** [netdata/dashboard#223]
Hello @jacekkolasa 

I wanted to just make a ticket of the changes i think we want to try look at for another iteration on the PostHog stuff. 

1. We want to use the default PostHog cookies so i think all we need to do for this is to not set `distinct_id` [here](https://github.com/netdata/dashboard/blob/posthog-test/src/domains/global/sagas.ts#L101) and hoping then the posthog library will handle it. 
2. Can we add a new event attribute called "netdata_machine_guid" = `machineGuid` in the `posthog.register` call (since we removing it in the bullet point above)
3. Can we add logic whereby PostHog is only turned on for demo servers and some dev servers that we can define in some way? Not sure what best option here is but the thinking is we would like to have it enabled for demo servers and our own few specific development machines on launch. If this is too messy or complicated i'm happy to just not do it, and instead maybe we just have our own internal version that just adds our dev servers to the list of demo servers. So not worth time if this is a complicated thing to do and all throwaway effort. 
4. ~~Manolis Vasilakis (@MrZammler) is working to add the few more config based event attributes to the agent backend events and i am asking him if we can ask make them available via the /api/v1/info endpoint. If so then we might have a few more event attributes we want to pull from there to add to the `posthog.register` call too. I'll update the issue when i have a list of what we want to add~~. (we will do this in a later dashboard release instead) 

Any questions just give me a ping.

**Comment by andrewm4894** [comment]
Update on this one. After chatting to Austin we are going to launch initially with the available info we have a the moment and then add the additional new event attributes @MrZammler is working on in a follow on release once we happy PostHog working. So for the `v2.12.0-alpha.5` posthog dashboard we only will be looking for points 1,2,3 above and will do point 4 at a later stage.

**Comment by jacekkolasa** [comment]
https://github.com/netdata/dashboard/pull/215 has been merged to master, i'll create a release and a pr for Netdata now.
As we discussed, posthog will work on demo servers and on any servers when `posthog-dev` flag will be `true`.

So, you'll need to do in the console:
```
localStorage.setItem("posthog-dev", "true")
```
and reload dashboard

**Comment by andrewm4894** [comment]
i think we ok to close this
