### ISSUE TITLE
unmask certain event attributes on demo sites

### ISSUE THREAD

**Issue by andrewm4894** [netdata/dashboard#241]
For demo sites we actually should not mask certain event attributes and understanding a bit more about our demo site traffic will actually be very useful for various things. 

So for demo sites we should just not register the masked values for the following attributes: $current_url, $pathname, $host 

Instead we should just let them be whatever the normal way posthog captures them are. 

I think we can do this by just not setting those attributes in the `posthog.register()` when on netdata demo sites.

**Comment by jacekkolasa** [comment]
it should be available today on nightlies
