### ISSUE TITLE
posthog send `host_collectors` as an array

### ISSUE THREAD

**Issue by andrewm4894** [netdata/dashboard#244]
It's looking like it will be better and easier to maintain and validate if we just send the json from /api/v1/info/ `collectors` as a string to PostHog. 

It can then be wrangled further down the pipeline and will be easier for data validation using this approach.

**Comment by andrewm4894** [comment]
adding to this, that we can actually just send the array into posthog without needing to serialize it to string. 

example using python:

```python
import posthog
from datetime import datetime
posthog.api_key = 'mqkwGT0JNFqO-zX2t0mW6Tec9yooaVu7xCBlXtHnt5Y'
posthog.host = 'https://posthog.netdata.cloud'
posthog.debug = True
# send an event
posthog.capture(
    distinct_id='andy-laptop',
    event='dev',
    timestamp=datetime.now(),
    properties={
        '$current_url': 'dev',
        '$pathname': 'dev',
        '$host': 'dev',
        '$ip': '127.0.0.1',
        'host_collectors': [
            {
                "plugin": "python.d.plugin",
                "module": "dockerhub"
            },
            {
                "plugin": "apps.plugin",
                "module": ""
            }
        ]
    }
)
```

And looks like this in Posthog: 

![image](https://user-images.githubusercontent.com/2178292/109719490-a1889a00-7ba0-11eb-972c-5ba68e3f555d.png)

**Comment by andrewm4894** [comment]
Just adding note to my future self. 

Once this is live we will also need to update these data processing events accordingly to just loop over the `host_collectors` array instead. 

https://github.com/netdata/posthog-netdata-event-processing/blob/main/index.js#L32

**Comment by andrewm4894** [comment]
Update: After looking at the backend events and making sure everything is consistent it would be best to keep the `host_collector_plugins` and `host_collector_modules` in addition to adding the `host_collectors` property. 

We will retire `host_collector_plugins` and `host_collector_modules` then if/when the backend can also send `host_collectors`. 

Maybe chat to me before doing anything on this one as it's changing a little day by day :)

**Comment by andrewm4894** [comment]
host_collector_plugins and host_collector_modules can now be deleted

**Comment by jacekkolasa** [comment]
it should be available today on nightlies
