### ISSUE TITLE
Turn posthog on for all agent dashboards and disable GA

### ISSUE THREAD

**Issue by andrewm4894** [netdata/dashboard#248]
As we are happy with the PostHog data from our demo servers we are now ready to turn it on by default for all agent dashboards. 

I think we should:

- Turn it on for all agent dashboards. 
- Disable the GA code but leave it there should we need to re-enable it (idea being we can then full remove it later as part of a final clean up).

@jacekkolasa does that sound ok to you? Or better to just take out the GA code now and easy to just add it back in if needed?

Whatever you think is best.

**Comment by jacekkolasa** [comment]
I also prefer to remove the code than to disable.
@andrewm4894 actually we import GTM, not GA - please confirm if you're OK with removing GTM.

**Comment by andrewm4894** [comment]
I will check first with @netdata/product and @thanos-karachalios @dim08 @manos-saratsis etc about the impact on the agent survey. I'll also double check with @novykh as i think he knows most about what's in GTM. I'll update here once i have a clear final picture.

**Comment by andrewm4894** [comment]
@jacekkolasa we are ok with removing GTM. I may need to make another issue to migrate the survey code from GTM into the dashboard, but waiting to see what product want in that regard.

So yep - all good to remove GTM from the agent dashboard.

**Comment by jacekkolasa** [comment]
we removed GTM, closing as it was released on netdata repo :)
