### ISSUE TITLE
[Bug]: `Preparing dashboard for printing...` pop up stays on the pdf when using Firefox

### ISSUE THREAD

**Issue by ilyam8** [netdata/dashboard#268]
SSIA, reported in https://github.com/netdata/netdata/issues/10946#issuecomment-828977520

<img width="948" alt="Screenshot 2021-04-29 at 16 24 46" src="https://user-images.githubusercontent.com/22274335/116557752-6b009e80-a907-11eb-9701-3bb99fdeefd3.png">

### Version

- Dashboard version: [v2.17.0](https://github.com/netdata/dashboard/releases/tag/v2.17.0)
- Firefox version: 88.0 (64-bit)

### Steps to reproduce

It is **not always reproducible**, sometimes PDF is clean.

- print the netdata dashboard using Firefox

**Comment by hugovalente-pm** [comment]
@jacekkolasa can this be closed?

**Comment by jacekkolasa** [comment]
@hugovalente-pm I made a fix but I haven't made a dashboard release to netdata/netdata. Not sure if that's worth doing, since we'll gonna replace whole dashboard anyway.

**Comment by hugovalente-pm** [comment]
yes, makes sense.. let's not waste time on that then
