### ISSUE TITLE
[Bug]: snapshot timeframe resets the to the last 300 seconds when using relative `after` and `before`

### ISSUE THREAD

**Issue by ilyam8** [netdata/dashboard#272]
Before i click on Export: `#;after=-900;before=0;theme=slate;help=false`
After i click on Export: `#;after=1620378965486;before=1620379325486;theme=slate;help=false`

Works correctly when after and before are absolute timestamps.

### Version

- Dashboard version: [v2.17.0](https://github.com/netdata/dashboard/releases/tag/v2.17.0)

### Steps to reproduce

- change the timeframe to nondefault _Last_ value using time quick selector.
- export a snapshot

**Comment by jacekkolasa** [comment]
@ilyam8 this is fixed now, please let me know if you'll see any problems with it
