### ISSUE TITLE
Rename index.html

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/dashboard#29]
A doubt @jacekkolasa , why do not rename here the `index.html` to `index-new.html` instead to do the during the installation?

**Comment by Ferroin** [comment]
Eventually this will be the only dashboard, and when that happens we'd have to coordinate a rename in this repo with a change in the agent repo. By just doing the rename on install, we only need to change one repo when we decide to retire the old dashboard.

**Comment by jacekkolasa** [comment]
That was exactly the idea, that is - to have that "hack with index-new" filename - in the single place. But if it's easier to do this in `dashboard`, I'd say let's just do it. It's not difficult to coordinate it :)
