### ISSUE TITLE
Issues detected on dashboard

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/dashboard#32]
I executed the following tests using Google Chrome and Mozilla Firefox:

- I moved from top to bottom Netdata dashboard to verify that all charts were displayed correctly.
- I used the direct zoom on charts using keyboard and I also used `+` and `-` to create zooms
- I tried to open alarms to visualize them.
- I raised alarms to verify that alarm centralization was working.
- I had one slave running to  be sure that the move from one host to other would not create problems with the charts.
- I hide dimensions and select multiple dimensions on different charts
- I repeat the previous tests with browser console opened to check possible problems with JS variables.

During the tests with latest dashboard the following issues were found:

- [x] Small charts used to describe cpu utilization are on top of text.
- [x] When I try to open Alarms using dashboard, the first time that I click on link it raises the error `Cannot load the required JS library: bootstrap-table`, but when I close the message and the alarm and I try to access again, everything works.
- [x] On the right side menu, `eBPF` and `Applications` has the same image, but `eBPF` is not showing.
- [x] When dashboard tries to access `badge.svg?chart=system.cpu&alarm=10min_cpu_iowait&refresh=auto:1` I receive `NS_ERROR_FAILURE`.
- [x] I am detecting in different times the message `scrollToId is not defined` on events onclick. I received now a different message on this variable`Uncaught ReferenceError: scrollToId is not defined`

**Comment by thiagoftsm** [comment]
Errors detected on 0.2.4:

- [ ] Due the fact we had a bug when I tried to open the alarm, I could not test the alarm on dashboard properly, now that it is working fine, I detected that when I click on alarm log, Netdata is not redirecting to another tab and of course I do not have the alarm centralized on screen.
- [ ] I am seeing these errors now : 
```
   Uncaught TypeError: Cannot read property 'isUsingGlobalRegistry' of undefined
    at Object.onClickRow (:19999/static/js/8.a36d9b89.chunk.js:2)
    at d.trigger (:19999/static/js/13.b3f47c79.chunk.js:1)
    at HTMLTableCellElement.<anonymous> (:19999/static/js/13.b3f47c79.chunk.js:1)
    at HTMLTableCellElement.dispatch (:19999/static/js/0.2dfc59a1.chunk.js:2)
    at HTMLTableCellElement.v.handle (:19999/static/js/0.2dfc59a1.chunk.js:2)
`` 
- [ ] This was only a warning, please, take a look whether it is necessary to change something:
```
DevTools failed to parse SourceMap: https://192.168.0.17:19999/static/js/6.e35c0fbe.chunk.js.map
DevTools failed to parse SourceMap: https://192.168.0.17:19999/static/css/1.883407c7.chunk.css.map
DevTools failed to parse SourceMap: https://192.168.0.17:19999/static/js/1.64f275f8.chunk.js.map
```

**Comment by thiagoftsm** [comment]
- [ ] While I was testing whether problem with dimensions resize was present on `system.cpu`, I decided to do the same with other chart with the same units, after I give a zoom in the chart `` and begin to hide dimensions I received the following error: 

```
react-dom.production.min.js:209 TypeError: Cannot read property '1' of undefined
    at chart-legend.tsx:211
    at Array.map (<anonymous>)
    at Y (chart-legend.tsx:199)
    at Ji (react-dom.production.min.js:153)
    at Uu (react-dom.production.min.js:175)
    at xa (react-dom.production.min.js:263)
    at Ec (react-dom.production.min.js:246)
    at wc (react-dom.production.min.js:246)
    at dc (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
ia @ react-dom.production.min.js:209
n.callback @ react-dom.production.min.js:226
vi @ react-dom.production.min.js:131
sa @ react-dom.production.min.js:212
Tc @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Qo @ react-dom.production.min.js:122
kc @ react-dom.production.min.js:248
dc @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Qo @ react-dom.production.min.js:122
Xo @ react-dom.production.min.js:123
Go @ react-dom.production.min.js:122
pc @ react-dom.production.min.js:240
notify @ Subscription.js:23
t.notifyNestedSubs @ Subscription.js:65
t.handleChangeWrapper @ Subscription.js:70
v @ redux.js:220
(anonymous) @ redux-saga-core.esm.js:1410
(anonymous) @ chart.tsx:127
highlightCallback @ dygraph-chart.tsx:418
S.mouseMove_ @ dygraph.js:1621
mouseMoveHandler_ @ dygraph.js:829
react-dom.production.min.js:123 Uncaught TypeError: Cannot read property '1' of undefined
    at chart-legend.tsx:211
    at Array.map (<anonymous>)
    at Y (chart-legend.tsx:199)
    at Ji (react-dom.production.min.js:153)
    at Uu (react-dom.production.min.js:175)
    at xa (react-dom.production.min.js:263)
    at Ec (react-dom.production.min.js:246)
    at wc (react-dom.production.min.js:246)
    at dc (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
```

**Comment by thiagoftsm** [comment]
- [ ] The `sign in` button is missing on Linux.

**Comment by thiagoftsm** [comment]
- [ ] When I do a refresh (pressing `CTRL + R`) the login disappears and I need to do another authentication.

**Comment by jacekkolasa** [comment]
@cakrit the last issue is hard for me to replicate and i'm starting to wonder if it's not because of specific configuration Thiago has (or old firefox version which his Slackware Linux has). Also, the SSO is being completely rewritten for new navbars, so this issue will never be present in stable Netdata.

Also, if we're having old dashboard as default (for now), then IMO it will make sense to merge this new Dashboard PR into master, and have it tested by our team, during everydays work.

**Comment by cakrit** [comment]
> @cakrit the last issue is hard for me to replicate and i'm starting to wonder if it's not because of specific configuration Thiago has (or old firefox version which his Slackware Linux has). Also, the SSO is being completely rewritten for new navbars, so this issue will never be present in stable Netdata.
> 
> Also, if we're having old dashboard as default (for now), then IMO it will make sense to merge this new Dashboard PR into master, and have it tested by our team, during everydays work.

Agreed, move ahead.
