### ISSUE TITLE
Can't view replicated node

### ISSUE THREAD

**Issue by vobruba-martin** [netdata/dashboard#320]
When trying to open netdata for child from parent netdata I see nothing but this error in JS console:

![Screenshot](https://user-images.githubusercontent.com/6897988/134322400-b4533d95-9c06-4563-bb66-d01f941bf26a.png)

Parent netdata version: v1.31.0-265-ge7cd69dba
Child netdata version: v1.19.0-10-g48525f9

**Comment by vobruba-martin** [comment]
@ilyam8 1.19 is the latest version I can compile on the server.

The problem seems to be in calling `/host/{child}/api/v1/info` from parent. Child v1.19.0 returns malformed JSON. See the `os_name` entry:
![json](https://user-images.githubusercontent.com/6897988/135506369-d4ffb9f7-7a2f-4321-90d5-e40267c9c7c5.png)

**Comment by ilyam8** [comment]
Did you try [pre-compiled static binary](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart-64)?

**Comment by vobruba-martin** [comment]
I've updated `/etc/os-release` file on chilld. From `NAME="Ubuntu"` to `NAME=Ubuntu`. After recompiling child netdata it is working now.

**Comment by vobruba-martin** [comment]
> Did you try [pre-compiled static binary](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart-64)?

Not yet. Maybe I will give it a try.

**Comment by ilyam8** [comment]
Well, I used a docker container as a child instance. It returns valid JSON `/api/v1/info` response

<details>
<summary>info response</summary>

```json
{
	"version": "v1.19.0",
	"uid": "99ac6c52-21f5-11ec-a03f-0242ac110002",
	"mirrored_hosts": [
		"a163ea3d9766"
	],
	"alarms": {
		"normal": 57,
		"warning": 0,
		"critical": 0
	},
	"os_name": "Alpine Linux",
	"os_id": "alpine",
	"os_id_like": "unknown",
	"os_version": "unknown",
	"os_version_id": "3.9.4",
	"os_detection": "/etc/os-release",
	"kernel_name": "Linux",
	"kernel_version": "5.10.47-linuxkit",
	"architecture": "x86_64",
	"virtualization": "hypervisor",
	"virt_detection": "/proc/cpuinfo",
	"container": "docker",
	"container_detection": "dockerenv",
	"collectors": [
		{
			"plugin": "apps.plugin",
			"module": ""
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/diskstats"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/softirqs"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/uptime"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/meminfo"
		},
		{
			"plugin": "idlejitter.plugin",
			"module": ""
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/net/dev"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/net/stat/nf_conntrack"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/loadavg"
		},
		{
			"plugin": "proc.plugin",
			"module": "ipc"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/net/sockstat"
		},
		{
			"plugin": "statsd.plugin",
			"module": "stats"
		},
		{
			"plugin": "cgroups.plugin",
			"module": "stats"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/interrupts"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/net/snmp"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/stat"
		},
		{
			"plugin": "netdata",
			"module": "stats"
		},
		{
			"plugin": "diskspace.plugin",
			"module": ""
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/net/ip_vs_stats"
		},
		{
			"plugin": "web",
			"module": "stats"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/net/netstat"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/sys/kernel/random/entropy_avail"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/vmstat"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/net/snmp6"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/net/softnet_stat"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/net/sockstat6"
		}
	]
}
```

</details>

But i get 

> Cannot read properties of undefined (reading 'reachable').

error.

**Comment by vobruba-martin** [comment]
Yes. Now I see the child dashboard without any errors in console via the parent.

**Comment by ilyam8** [comment]
Thanks! That is good. There is definitely a bug, but very minor and considering that v1.19.0 is very old I am going to close this issue as "wontfix".
