### ISSUE TITLE
[BUG] Chart still plays when export snapshot modal is open

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/dashboard#328]
##### Bug report summary

Reproduced on katsuna

##### OS / Environment

Reproduced on [katsuna](http://n1.katsuna.com:19999)

##### Netdata version

v1.31.0-366-nightly

##### Installation method

Don't know

##### Component Name

Snapshots with Play/Pause controls

##### Steps To Reproduce

1. Check that your chart is playing
2. Open the export snapshot modal
3. Chart continues to play on the background

##### Expected behavior

Chart should be paused while user has the export snapshot modal open, modal is referent to the period the user was seeing when he asked the modal to open

**Comment by jjtsou** [comment]
Fixed on https://github.com/netdata/netdata/pull/11743
