### ISSUE TITLE
[BUG] Datetime picker not integrated with snapshots

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/dashboard#329]
##### Bug report summary

The new datetime picker is not integrated correctly with the snapshot feature.

If I change my time selection using the datetime picker this isn't taken into consideration when I try to export a snapshot, once I interact with the charts to pan, zoom, etc. and then when I try to export the snapshot the current datetime selection (triggered by the interaction on the chart) it is taken into consideration

##### OS / Environment

Reproduced on [katsuna](http://n1.katsuna.com:19999/)

##### Netdata version

v1.31.0-366-nightly

##### Installation method

Don't know

##### Component Name

Snapshots with Datetime picker

##### Steps To Reproduce

1. Check that datetime picker is for 15min
2. Go to export a snapshot and for a precision of 1 second per point see that you have 540 points per dimension. Expected size on disk 2.6 MB, at browser memory 2.5 MB (witk pako.deflate.base64)
3. Change the datetime picker is for 24 hours/1 day
4. Go to export a snapshot and for a precision of 1 second per point see that you still have 540 points per dimension. Expected size on disk 2.6 MB, at browser memory 2.5 MB (witk pako.deflate.base64)
5. Pan the chart with your mouse
6. Go to export a snapshot and see that precision was automatically changed to 113 seconds per point, if you place it 1 second per point you see. "The snapshot will have 86676 points per dimension. Expected size on disk 324.9 MB, at browser memory 307.8 MB."

##### Expected behavior

The changes on datetime picker should be reflected on the snapshot feature

**Comment by jjtsou** [comment]
Fixed on https://github.com/netdata/netdata/pull/11743
