### ISSUE TITLE
Can't plot tiny plots with netdata

### ISSUE THREAD

**Issue by mlubej** [netdata/dashboard#336]
Hi!

I'm trying to plot small plots on the bottom of my screen using [uebersicht](https://github.com/felixhageloh/uebersicht) and netdata.

I am able to achieve the following

<img width="1459" alt="image" src="https://user-images.githubusercontent.com/37869250/140834778-c858bf0c-e531-4dda-9d33-f3600ef57aa3.png">

However, I would like to even further decrease the height of the box, but the issue is that the content then is cut off, instead of being scaled. Is there a solution for this? 

This is what it looks like after

<img width="1454" alt="image" src="https://user-images.githubusercontent.com/37869250/140834874-20220ec2-b589-48fa-8eea-22d5ad890fca.png">

Thanks!

**Comment by jacekkolasa** [comment]
hi @mlubej !
Unfortunately dygraph charts by default don't scale to be smaller than 100px.
But it's possible if you'll override locally some css in dashboard.slate.css
```
.netdata-container-with-legend {
  /* min-height: 99px; */
}
```
Also, you can remove the title so the chart itself takes more space:
```
data-title=""
```


Alternative way, if you're ok with not having legend and labels, is to have sparkline chart:
```
data-dygraph-theme="sparkline"
```
WIll some of those options work for you?

**Comment by mlubej** [comment]
Thanks a lot @jacekkolasa for the information and providing the alternatives. These sparklines are great!

**Comment by mlubej** [comment]
This is what I came up with, thanks a lot!

<img width="1536" alt="image" src="https://user-images.githubusercontent.com/37869250/140973828-1190adc4-cc4f-45b5-9c71-d73b3b6c85b2.png">
