### ISSUE TITLE
[Bug]: agent dashboard `after` and `before` url params not respected

### ISSUE THREAD

**Issue by andrewm4894** [netdata/dashboard#346]
### Bug description

If i try to load an agent dashboard url with specific `after` and `before` params they get overwritten on page load with -420 and 0 respectively. 

link to internal slack thread on this: https://netdata-cloud.slack.com/archives/CQELFFSUB/p1642003156001200

### Expected behavior

The specific `after` and `before` url params take precendence. 

### Steps to reproduce

1. scroll to a specific url with an after and before populated.
2. copy and paste the url into a new tab.
3. refresh the page - you do not go to the after and before you expected.
...

### Installation method

kickstart.sh

### System info

```shell
no
```

### Netdata build info

```shell
no
```

**Comment by ilyam8** [comment]
I installed different versions of the dashboard:
 - v2.20.2 - **with no** bug.
 - v2.20.7 - **with** the bug.

**Comment by ilyam8** [comment]
Big thanks, @jjtsou 👍
