### ISSUE TITLE
[BUG] Not getting modal to Cloud on re-install of Netdata Agent

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/dashboard#376]
When a re-installation of a Netdata Agent is performed, following the [uninstall setps](https://learn.netdata.cloud/docs/agent/packaging/installer/uninstall), I don't get the modal to tell me about to Cloud. This happens because there are some references to the GUID from the previous installation in `/var/lib/netdata/registry`.

In a scenario like this the user should still see a modal saying that the current node is not connected to Cloud because we see:
* `claimed` as `true`
* `reachable` as `false`

On user information I saw:
* `userStatus` as `loggedIn`
* `userNodeStatus` as `noAccess`

Case **MODAL TO INFORM USER WE ARE FALLING BACK TO AGENT DASHBOARD** was reviewed on `USER_SAVED_PREFERENCE` to say `!= AGENT`

```
If {USER_SAVED_PREFERENCE} != AGENT
And
    {USER_STATUS} = LOGGED_IN or EXPIRED_LOGIN
And
   {NODE_CLAIMED_STATUS} = CLAIMED
And
   {NODE_LIVENESS} = NOT_LIVE
And 
   {USER_NODE_ACCESS} = ACCESS_OK 
–> Open modal with “Oops! This node has lost connection to Netdata Cloud!”

**Comment by ivangergo3** [comment]
Tested, all looks good.
