### ISSUE TITLE
[Bug]: Update check on agent dashboard is broken.

### ISSUE THREAD

**Issue by Ferroin** [netdata/dashboard#393]
The current update check code used to determine if there is a newer version of the agent or not appears to be built on a couple of very specific assumptions:

- The most recent release on GitHub is the highest possible version number.
- Builds in general are always assumed to have a version number that is strictly greater than any previous builds.
- https://www.googleapis.com/storage/v1/b/netdata-nightlies/o/latest-version.txt is only updated for nightly builds.

The final assumption has never actually been the case, though this has rarely actually mattered.

The other two assumptions used to be the case, but are no longer the case due to shifts in our release engineering process (in short, we can now publish patch releases for any minor release starting with v1.34.0 even if a newer minor release has been created).

The failures of these assumptions are leading to update checks failing in some cases and incorrectly reporting newer versions when they should not.

Correct behavior for this check should, in light of the recent changes, be as follows:

- For nightly builds, https://raw.githubusercontent.com/netdata/netdata/master/packaging/version should be used instead of the above-mentioned GCS URI, and a newer version should only be reported if the version in that file ends with `-nightly`. This avoids the final assumption above and also future-proofs the check (we will almost certainly always be using GitHub, but we may move away from GCS for nightly build storage).
- For stable releases, a list of releases must be fetched from GitHub and then parsed to find the highest release version listed instead of relying on GitHub to give us the most recently created release (which _may_ not be the highest version). This avoids the first assumption above. We may be able to do this in a single API query if we leverage the GitHub GraphQL API instead of the REST API.

**Comment by AlexNti** [comment]
Closing, this seems to be fixed.
