### ISSUE TITLE
[BUG] Replicated Nodes search box disappears

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/dashboard#394]
## Description

When a user tries to search for a replicated node, under a parent node, the search box disappears when a name for a non-existing node is introduced

## Steps
1. Go to an Agent Dashboard for a parent agent
2. On the `Replicated Nodes` try to search for a child node that doesn't exist
3. Notice that the search box disappears

![chrome_fisu4IAHpU](https://user-images.githubusercontent.com/82235632/164550036-21b0738a-f5ac-4e57-b53e-e53e0875f93b.gif)

## Expected behaviour

Search box should work like the Visited  Nodes one.

![chrome_buAIGJ2R6h](https://user-images.githubusercontent.com/82235632/164550210-4f57a32c-33b4-494f-ba0c-cbb366d6e12a.gif)

**Comment by hugovalente-pm** [comment]
@jacekkolasa this bug was reported by @ktsaou on a discussion with me and @novykh, @novykh mentioned for you to tackle it

cc/ @dionysis-netdata (since it falls under Navigation) @sashwathn (since Jacek in on Alerts team)

**Comment by hugovalente-pm** [comment]
@jacekkolasa you are assigned to this ticket, just checking if you can tackle

**Comment by jacekkolasa** [comment]
@hugovalente-pm yes, thanks a lot for pinging

**Comment by jacekkolasa** [comment]
On production. Thanks @BillKalaitzis for fixing the deployment!
