### ISSUE TITLE
[Feat]: Disable "Discover the free benefits of Netdata Cloud"

### ISSUE THREAD

**Issue by Emporea** [netdata/dashboard#429]
### Problem

I disabled cloud functionality in cloud.conf but this Banner is still present and i want it to be removed.

### Description

![image](https://user-images.githubusercontent.com/21969523/178604320-86d87dd3-1a85-4b17-917d-6e36a5bc5cb1.png)

I want the banner removed.

### Importance

nice to have

### Value proposition

1. less used space for more important stuff than some cloud functionality i will never use. 
2.
3.
...

**Comment by MrZammler** [comment]
Hi @Emporea !

One way this might work, is if you try to compile from source with `--disable-cloud`. You can try with `--build-only` in kickstart to do a build, and `--disable-cloud`. There is more info [here](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart/)

Haven't checked myself if this would work, can you give it a try?

Also if it's not a problem, could you tell us why you don't plan to use Netdata Cloud?

**Comment by Ferroin** [comment]
@MrZammler The approach you describe does work, but is not realistic. If Cloud support is disabled at runtime, we should not be showing this banner. Most of our users are using pre-built binaries, and many may have no other choice. We shouldn’t be telling people ‘You have to do a special install method that may not even work correctly on your system, will take a long time,a and will use a bunch of system resources just so you can get rid of us nagging you about something you already know you will no be using.’

That said, I would also argue that it should be possible for the user to just dismiss it, but I doubt that I will ever manage to convince the product team (or Costa) of this.

**Comment by thepheer** [comment]
> That said, I would also argue that it should be possible for the user to just dismiss it, but I doubt that I will ever manage to convince the product team (or Costa) of this.

Oof, I guess the project reaches the point where I stop using/recommending it. I appreciate the honesty though.

**Comment by Emporea** [comment]
Actually I managed to remove it by downgrading to v1.35.1.

That cant be the solution for long tho.
@MrZammler Rather than answering why I, as a selfhosting enthusiast, dont wanna use an external system monitoring cloud provider you should explain to me why i should use it in the first place.

**Comment by thepheer** [comment]
Yup, same here.

**Comment by SaswatPadhi** [comment]
Same issue here and it's very annoying.

If a user has placed `enabled = no` in "cloud.conf", they surely are aware of Netdata Cloud and chose not to use it for whatever reason they have. I think Netdata should respect that.

It is quite unrealistic to expect people to ditch installing netdata from their OS package manager and instead rebuild netdata from source with special flags.
Sorry to be blunt, but that's basically like intentionally placing malware in a package and asking people to comment it out and recompile if they don't want it.

**Comment by MrZammler** [comment]
Hi guys!

Fair points. Please allow us a while to check this, and I will update this thread with more information soon.

Thanks for you input!

**Comment by hugovalente-pm** [comment]
this has been tackled https://github.com/netdata/dashboard/releases/tag/v2.29.0 and will be available on today's nightly release of the Netdata Agent.

**Comment by Emporea** [comment]
Can confirm that it works. Thank you guys to respect such community requests!

**Comment by SaswatPadhi** [comment]
Thank you!
