### ISSUE TITLE
How to disable "Netdata Monitoring" section ?

### ISSUE THREAD

**Issue by Damolx** [netdata/dashboard#435]
Hello folk,

Since the latest update (1.35.x) a lot of metrics were enabled automatically even if i disabled them in the netdata.conf file.
The update re-organised netdata.conf and some parameters are no longer valid, the comment "#section is not used" is shown above them.

For plugins i figured out easily how to enable/disable but for the "Netdata Monitoring" section i did not find the solution.

How can i disable them now ? 

Thanks a lot.

![net](https://user-images.githubusercontent.com/52316560/181937453-3b8caa75-a5de-4c57-bd7f-1559b1e698e0.jpg)

**Comment by MrZammler** [comment]
Hi @Damolx 

There is currently no way to disable this section, but it is something we discussed briefly at some point. Stay tuned!!

**Comment by Damolx** [comment]
Thanks for the reply !
