### ISSUE TITLE
Slave overwrite menu

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/dashboard#74]
When I am selecting an slave on the menu:
![err9](https://user-images.githubusercontent.com/49162938/80120440-86113380-857a-11ea-8ad4-ceb6e08af0b4.png)

Instead to open in the main screen, the response is overwritten the menu:

![err10](https://user-images.githubusercontent.com/49162938/80120481-99bc9a00-857a-11ea-915e-26b37f3cfc87.png)

**Comment by jacekkolasa** [comment]
@thiagoftsm thanks for report, it's fixed now
