### ISSUE TITLE
wrong message?

### ISSUE THREAD

**Issue by ktsaou** [netdata/dashboard#87]
https://github.com/netdata/dashboard/blob/8dd6b350d95ca46a46eb79a4053915448ee6d932/src/components/notifications/notifications.tsx#L36-L37

This message has 2 issues:

1. `This agent cannot connect to Netdata Cloud`, what does it mean? The browser cannot connect to Netdata Cloud or the agent is not connected to netdata cloud (lost ACLK)?

2. `Please talk to system's administrator for more information.` assumes that the user is not the system administrator and it is funny and awkward if the user is indeed the admin. So, do not make assumptions on corporate processes and procedures. Just state the problem and let the user decide how to deal with it.

**Comment by jacekkolasa** [comment]
cc @manos-saratsis @rduffield

**Comment by manos-saratsis** [comment]
@ktsaou 1. This message is shown via a toast notification on the agent dashboard when the agent cannot connect to Cloud through ACLK. Is triggered when the required dependencies are missing to install libwebsockets.

2. We do not have any suggestions so users recover from the error. There are a couple of issues related to this like:
- When users build through kickstart we do not store install logs (https://github.com/netdata/netdata/issues/9348)
- Older installations do not try to install dependencies like cmake

We will improve the message to "Please install the required dependencies, uninstall and install again your agent" and link to a documentation page @Ferroin and Joel to assist

**Comment by manos-saratsis** [comment]
@jacekkolasa Can you please change the message to "To access Cloud install again your agent via the kickstart script" and add the link:
https://learn.netdata.cloud/docs/agent/packaging/installer#automatic-one-line-installation-script

**Comment by jacekkolasa** [comment]
fixed in https://github.com/netdata/dashboard/pull/155, currently in Netdata nightlies
