### ISSUE TITLE
Missing units

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/dashboard#88]
Netdata dashboard is missing the following conversion:

```
'bytes/s': {
            'bytes/s': 1,
            'kilobytes/s': 1024,
            'megabytes/s': 1024 * 1024,
            'gigabytes/s': 1024 * 1024 * 1024,
            'terabytes/s': 1024 * 1024 * 1024 * 1024
        },

 'B/s': {
            'B/s': 1,
            'KiB/s': 1024,
            'MiB/s': 1024 * 1024,
            'GiB/s': 1024 * 1024 * 1024,
            'TiB/s': 1024 * 1024 * 1024 * 1024
        },
```

The PR https://github.com/netdata/netdata/pull/9333 is fixing this for the old dashboard, but we also need to fix here.

**Comment by ilyam8** [comment]
https://github.com/netdata/dashboard/search?q=KiB%2Fs&unscoped_q=KiB%2Fs

**Comment by thiagoftsm** [comment]
@jacekkolasa , please, is it possible to fix this until the release on Wednesday?

**Comment by jacekkolasa** [comment]
@thiagoftsm sure, i'll do that today. There's one problem - dashboard repo is now ahead of version in netdata repo, so i'll need to create a branch off some commit in history. I don't want to release the newest version because i think it can have a bug and it's not tested enough.
